# Clave única. DEBE SER ÚNICA en SonarQube.
sonar.projectKey=python-jenkins-demo

# Nombre visible en la interfaz web de SonarQube
sonar.projectName=Demo Python CI/CD

# La versión del proyecto
sonar.projectVersion=1.0

# Archivos o carpetas que contienen tu código fuente.
sonar.sources=app.py

# El lenguaje (ayuda a SonarQube a usar las reglas correctas)
sonar.language=py
